### PR TITLE
docs: fix table of contents links

### LINKED ISSUE #31: [Documentation Update]: Fix link in 'Table of Contents' required
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Some of the links in the 'Table of Contents' section of the EEADME.md file are broken.``

### Suggested Change

Fix the links in the 'Table of Contents' section so they navigate to the correct section.

### Rationale

This will improve the user experience.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by mostafahanafi**
fix #31 - links in readme table of contents now navigate to appropriate sections

### CODE REVIEW

**Comment by dmotts** [comment]
Thank you for your contribution, @mostafahanafi!

**Comment by dmotts** [comment]
Would mind telling me how you discovered this project? #32

**Comment by mostafahanafi** [comment]
@dmotts no worries :) i discovered it while looking through issues with the hacktoberfest label and came across #31

**Comment by dmotts** [comment]
Cool. Thanks again for your contribution, have a wonderful day!

**Pull request merged**
